name: Build and Release Extension

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to create releases
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build extension
        run: npm run build
      
      - name: Package extension as ZIP
        run: |
          cd dist
          zip -r ../url-switch.zip .
          cd ..
          
      - name: Create GitHub Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            url-switch.zip
          body: |
            ## Download Links
            
            - [Download ZIP File](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/url-switch.zip)
            
            ## Installation Instructions
            
            1. Download the ZIP file
            2. Unzip the file to a local folder
            3. In Chrome, go to `chrome://extensions/`
            4. Enable "Developer mode" in the top-right
            5. Click "Load unpacked" and select the unzipped folder
            
            ## Release Notes
          draft: false
          prerelease: false
          generate_release_notes: true
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extension-files
          path: |
            url-switch.zip 